export const experiences = [
	{
		company: '',
		time: '',
		title: '',
		location: '',
		description: '',
	},
	// {
	// 	company: 'Radium Institute (Institut du Radium)',
	// 	time: '1914 - 1934',
	// 	title: 'Director',
	// 	location: 'Paris, France',
	// 	description: 'Led groundbreaking studies on radioactivity and mentored future Nobel Prize laureates.',
	// },
];

export const education = [
	{
		school: '',
		time: '',
		degree: '',
		location: '',
		description: '',
	},
	// {
	// 	school: 'University of Paris',
	// 	time: '1891 - 1895',
	// 	degree: 'Master’s in Physics and Mathematics',
	// 	location: 'Paris, France',
	// 	description: 'Graduated at the top of her class in physics and second in mathematics.',
	// },
];

export const skills = [
	{
		title: '',
		description: '',
	},
	// {
	// 	title: 'Experimental Techniques',
	// 	description: 'Spectroscopy, Isolation of Radioactive Elements, Radiation Measurement',
	// },
];

export const publications = [
	{
		title: 'Π2-rule systems and inductive classes of Gödel algebras',
		authors: 'Rodrigo Nicolau Almeida',
		journal: 'Annals of Pure and Applied Logic, Volume 176, Issue 4, April 2025',
		time: '2025',
		link: 'https://www.sciencedirect.com/science/article/pii/S0168007225000016?via%3Dihub',
		abstract: 'In this paper we present a general theory of Π2-rules for systems of intuitionistic and modal logic. We introduce the notions of -rule system and of an inductive class, and provide model-theoretic and algebraic completeness theorems, which serve as our basic tools.',
	},
	{
		title: 'Polyatomic logics and generalized Blok–Esakia theory',
		authors: 'Rodrigo Nicolau Almeida',
		journal: 'Journal of Logic and Computation, Volume 34, Issue 5, July 2024, Pages 887–935',
		time: '2023',
		link: 'https://academic.oup.com/logcom/advance-article-abstract/doi/10.1093/logcom/exad043/7198104?redirectedFrom=fulltext',
		abstract: 'This paper presents a novel concept of a polyatomic logic and initiates its systematic study. ',
	},
];

export const accepted_articles = [
	{
		title: "Unification with Simple Variable Restrictions and Admissibility of Pi2-rules",
		authors: "Rodrigo Nicolau Almeida, Silvio Ghilardi",
		abstract: "We develop a method to recognize admissibility of Π2-rules, relating this problem to a specific instance of the unification problem with linear constants restriction, called here unification with simple variable restriction. It is shown that for logical systems enjoying an appropriate algebraic semantics and a finite approximation of left uniform interpolation, this unification with simple variable restriction can be reduced to standard unification. As a corollary, we obtain the decidability of admissibility of Π2-rules for many logical systems.",
		time: "Accepted at AIML 2024 Proceedings",
		journal: " ",
		link: "https://rodrigonalmeida.github.io/papers/papers/Unification_with_Simple_Variable_Restrictions_and_Admissibility_of__2.pdf"
	},
	{
		title: "A Coalgebraic Semantics for Intuitionistic Modal Logic",
		authors: "Rodrigo Nicolau Almeida, Nick Bezhanishvili",
		abstract: "We give a new coalgebraic semantics for intuitionistic modal logic. In particular, we provide a coalgebraic representation of intuitionistic descriptive modal frames and of intuitonistic modal Kripke frames based on image-finite posets.",
		time: "Accepted at AIML 2024 Proceedings",
		journal: " ",
		link: "https://rodrigonalmeida.github.io/papers/papers/A_Coalgebraic_Semantics_for_Intuitionistic_Modal_Logic.pdf"
	}
	{
		title: "Maximality Principles in Modal Logic and the Axiom of Choice",
		authors: "Rodrigo Nicolau Almeida, Guram Bezhanishvili",
		abstract: "We investigate the set-theoretic strength of several maximality principles that play an important role in the study of modal and intuitionistic logics. We focus on the well-known Fine and Esakia maximality principles, present two formulations of each, and show that the stronger formulations are equivalent to the Axiom of Choice (AC), while the weaker ones to the Boolean Prime Ideal Theorem (BPI). ",
		time: "Accepted at Fundamenta Mathematicae",
		journal: " ",
		link: "https://arxiv.org/abs/2412.13706"
	},
]

export const submitted_articles = [
		{
		title: "Colimits of Heyting Algebras through Esakia Duality",
		authors: "Rodrigo Nicolau Almeida",
		abstract: "We generalize the construction, due to Ghilardi, of the free Heyting algebra generated by a finite distributive lattice, to the case of arbitrary distributive lattices. Categorically, this provides an explicit construction of a left adjoint to the inclusion of Heyting algebras in the category of distributive lattices.",
		time: "Submitted on 12 Feb 2024 (v1), last revised 13 Nov 2024 (this version, v3)",
		journal: " ",
		link: "https://arxiv.org/abs/2402.08058"
	}
]

export const seminars = [
	{
	title: "LAC Seminar Milan (08/05/2025): Pitts problem and Higher-Order Uniform Interpolation"
	link: "https://rodrigonalmeida.github.io/papers/slides/Milan___Pitts_problem_and_Higher_Order_Uniform_Interpolation.pdf"
	}
	{
	title: "Birmimgham (04/04/2025) Heyting algebras one step at a time"
	link: "https://rodrigonalmeida.github.io/papers/slides/Birmimgham___Heyting_algebras_one_step_at_a_time.pdf"
	}
	{
		title: "LLAMA (06/11/2024) Colimits and Free Constructions of Heyting Algebras Through Esakia Duality",
		link: "https://rodrigonalmeida.github.io/papers/slides/LLAMA___Colimits_and_Free_Constructions_of_Heyting_Algebras.pdf"
	},
	{
		title: "AIML (19/08/2024) Coalgebraic Semantics for Intuitionistic Modal Logic",
		link: "https://rodrigonalmeida.github.io/papers/slides/AIML___Coalgebraic_Semantics_for_Intuitionistic_Modal_Logic.pdf"
	},
	{
		title: "AIML (19/08/2024) Unification with Simple Variable Restrictions and Admissibility of Pi2 Rules",
		link: "https://rodrigonalmeida.github.io/papers/slides/AIML___Unification_with_Simple_Variable_Restrictions_and_Admissibility_of___Pi2_rules.pdf"
	},
	{
		title: "TACL (04/07/2024) Colimits of Heyting Algebras Through Esakia Duality",
		link: "https://rodrigonalmeida.github.io/papers/slides/TACL___Colimits_of_Heyting_Algebras_Through_Esakia_Duality.pdf"
	},
	{
		title: "LATD (11/12/2023) Inductive Rule Classes of Goedel Algebras",
		link: "https://rodrigonalmeida.github.io/papers/slides/LATD___Inductive_Rule_Classes_of_Godel_Algebras.pdf"
	},
	{
		title: "LLAMA (13/04/23) Goldblatt-Translation Revisited",
		link: "https://rodrigonalmeida.github.io/papers/slides/LLAMA_Presentation___Goldblatt_Translation_Revisited.pdf"
	},
	{
		title: "PhD Logic Day (23/06/23) Structural Completeness and bi-IPC",
		link: "https://rodrigonalmeida.github.io/papers/slides/PhD_Logic_Day___Structural_Completeness_and_bi_IPC.pdf"
	},
	{
		title: "Infinitary Completeness Theorems and Rasiowa-Sikorski Lemmas",
		link: "https://rodrigonalmeida.github.io/papers/slides/Infinitary_Completeness_Theorems__Representation_and_Intuitionistic_Logic.pdf"
	}
]

export const abstracts = [
	{
		title: "LATD (2025) (with N. Bezhanishvili and A. Cleani) A Dual Proof of Blok's Lemma ",
		link: "https://rodrigonalmeida.github.io/papers/abstracts/LATD2025_paper_53.pdf"
	},
	{
		title: "(TACL 2024) Colimits of Heyting algebras through Esakia duality",
		link: "https://rodrigonalmeida.github.io/papers/abstracts/TACL_2024_paper_19.pdf"
	},
	{
		title: "(LATD 2023) Universal and Inductive Rule Classes of Godel Algebras",
		link: "https://rodrigonalmeida.github.io/papers/abstracts/Abstract___LATD___Universal_and_Inductive_Classes_of_Godel_Algebras.pdf"
	},
	{
		title: "(TBILLC 2023) The Goldblatt Translation Revisisted",
		link: "https://rodrigonalmeida.github.io/papers/abstracts/Abstract___TbILLC___Goldblatt_Translation_Revisited.pdf"
	}
]

export const teaching = [
	{
		title: "Mathematical Structures in Logic 2025",
		position: "Teaching Assistant",
		collaboration: ""
	},
	{
		title: "Logic and Computability 2024",
		position: "Teacher",
		collaboration: "(with Daniël Otten)"
	},
	{
		title: "Introduction to Modal Logic (2021,2022 and 2023)",
		position: "Teaching Assistant",
		collaboration: ""
	},
	{
		title: "Model Theory (2023 and 2024)",
		position: "Teaching Assistant",
		collaboration: ""
	},
	{
		title: "Mathematical Proof Methods in Logic 2023",
		position: "Teaching Assistant",
		collaboration: ""
	},
	{
		title: "Axiomatic Set Theory 2022",
		position: "Teaching Assistant",
		collaboration: ""
	}
]

export const thesis_supervision = [
	{
		title: "Sarah Dukic",
		student_link: "",
		collaboration: "(co-supervised with Nick Bezhanishvili)",
		time: "in progress"
	},
	{
		title: "David Quinn Alvarez",
		student_link: "https://www.dqalvarez.me/",
		collaboration: "(co-supervised with Nick Bezhanishvili)",
		time: "2024"
	}
]

export const notes = [

] 
//example to add
// {
// title: "Title of Note",
// link: "url"
// }
